- name: Install containerd
  package:
    name: containerd
    state: present

- name: Create containerd directory
  file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: Create containerd config file
  file:
    path: /etc/containerd/config.toml
    state: touch
    mode: '0755'

- name: Generate containerd default config
  shell: containerd config default
  register: containerd_config

- name: Print output to file
  copy:
    content: "{{containerd_config.stdout}}"
    dest: /etc/containerd/config.toml

- name: replace line
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^(.*)SystemdCgroup = false(.*)$'
    line: 'SystemdCgroup = true'
    backrefs: yes


